spring.application.name=SegundoProyectoSpringMySQL

#Configuraciï¿½n de MySQL
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/gestion-reservas
spring.datasource.url=postgresql://gestion_reservas_user:UjhzRqAZoP1NKdxFPLveQUCMzH5q58du@dpg-d4mn91chg0os73bvr7h0-a/gestion_reservas
#spring.datasource.username=root
#spring.datasource.password=root
spring.datasource.username=gestion_reservas_user
spring.datasource.password=gestion_reservas_user
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostrar SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
